MvcProjeKampi/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class HeadingController : Controller
    {
        // GET: Heading

        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());

        public ActionResult Index()
        {
            var HeadingList = hm.GetList();
            return View(HeadingList);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            //DROPDOWN İÇİN 
            List<SelectListItem> valueCategory = (from x in cm.GetList()   //category listesi getirildi
                                                  select new SelectListItem  //selectListItem içinde değerleri atılıyor
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList(); //Bütün işlem listeye dönüştürülüyor
            ViewBag.category = valueCategory; // Controller'da oluşturulan bir yapıyı View kısmına taşımak için kullanılır.


            List<SelectListItem> valueWriter = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurname,
                                                    Value = x.WriterID.ToString()
                                                }).ToList();
            ViewBag.writer = valueWriter;



            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading heading)
        {
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            hm.HeadingAdd(heading);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            //DROPDOWN İÇİN 
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.category = valueCategory;

            var HeadingValue = hm.GetByID(id);
            return View(HeadingValue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading heading)
        {
            hm.HeadingUpdate(heading);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult DeleteHeading(int id)
        {
            var HeadingValue = hm.GetByID(id);
            HeadingValue.HeadingStatus = !HeadingValue.HeadingStatus;
            hm.HeadingDelete(HeadingValue);
            return RedirectToAction("Index");
        }

    }
}

MvcProjeKampi/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h2>Yeni Başlık Ekleme</h2>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x=>x.CategoryID ,(List<SelectListItem>)ViewBag.category , new {@class="form-control"})
        @Html.ValidationMessageFor(x => x.CategoryID)
        <br />
        @Html.Label("Yazar")
        @Html.DropDownListFor(x => x.WriterID ,(List<SelectListItem>) ViewBag.writer , new {@class ="form-control"}  )
        @Html.ValidationMessageFor(x => x.WriterID)
        <br />
        <button class="btn btn-info">Başlık Ekle</button>



    </div>
}

MvcProjeKampi/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading




@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Güncelleme</h2>

@using (Html.BeginForm("EditHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık ID")
        @Html.TextBoxFor(x => x.HeadingID, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
        <br />
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, htmlAttributes: new { @class = "form-control" })
        <br />
        @Html.Label("Tarih")
        @Html.TextBoxFor(x => x.HeadingDate, htmlAttributes: new { @class = "form-control" })
        <br /> 
        @Html.Label("Yazar ")
        @Html.TextBoxFor(x => x.WriterID, htmlAttributes: new { @class = "form-control" })
        <br />
        @Html.Label("Kategoriler")
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.category, htmlAttributes: new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Bilgileri Güncelle</button>


    </div>
}

MvcProjeKampi/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{ string color = "";
    string statusColor = "";}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->

    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 10%" >
                                Oluşturan Yazar
                            </th>
                            <th style="width: 10%" class="text-center">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge-warning";
                            }
                            else
                            {
                                color = "badge badge-success";
                            }

                            if (item.HeadingStatus)
                            {
                                statusColor = "badge badge-info";
                            }
                            else
                            {
                                statusColor = "badge badge-danger";
                            }


                            <tr>
                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                            <p>@item.Writer.WriterName</p>
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@statusColor">@item.HeadingStatus</span>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Yazılar
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingID">
                                        <i class="fas fa-trash">
                                        </i>
                                        @(item.HeadingStatus ? "Pasifleştir" : "Aktifleştir")
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>  
</body>
</html>

<a class="btn btn-primary" href="/Heading/AddHeading/">Yeni Başlık Ekle</a>